=== Reblexis/datove-formaty/NPRG036-T3G1-HW3/3/xml/schemas/schema-3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.com/schema-3"
           xmlns="http://www.example.com/schema-3"
           xmlns:tns="http://www.example.com/schema-3"
           xmlns:xml="http://www.w3.org/XML/1998/namespace"
           elementFormDefault="qualified">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="https://www.w3.org/2009/01/xml.xsd" />
    <xs:complexType name="langElement">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="phoneNumberType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\+[0-9]{3}-[0-9]{3}-[0-9]{3}-[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="Person">
        <xs:sequence>
            <xs:element name="firstName" type="tns:langElement"/>
            <xs:element name="lastName" type="tns:langElement"/>
            <xs:element name="mobileNumber" type="tns:phoneNumberType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="Teachers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Teacher" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="tns:Person">
                                <xs:sequence>
                                    <xs:element name="salary" type="xs:integer"/>
                                    <xs:element name="Subject" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="name" type="tns:langElement"/>
                                                <xs:element name="name" type="tns:langElement"/>
                                                <xs:element name="code" type="xs:string"/>
                                            </xs:sequence>
                                            <xs:attribute name="id" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="Building" minOccurs="0" maxOccurs="1">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="address" type="tns:langElement"/>
                                                <xs:element name="name" type="tns:langElement"/>
                                            </xs:sequence>
                                            <xs:attribute name="id" type="xs:anyURI" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute name="id" type="xs:anyURI" use="required"/>
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Reblexis/datove-formaty/NPRG036-T3G1-HW3/3/xml/data/data-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Teachers xmlns="http://www.example.com/schema-3"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.example.com/schema-3 ../schemas/schema-3.xsd">

    <Teacher>
        <firstName xml:lang="cs">Jan</firstName>
        <lastName xml:lang="cs">Novák</lastName>
        <mobileNumber>+420777111222</mobileNumber>
        <salary>55000</salary>
        <Subject>
            <name xml:lang="cs">Programování I</name>
            <code>NPRG030</code>
        </Subject>
        <Subject>
            <name xml:lang="cs">Algoritmy a datové struktury</name>
            <code>NPRG031</code>
        </Subject>
        <Building>
            <address xml:lang="cs">Malostranské náměstí 25, Praha 1</address>
            <name xml:lang="cs">Budova MFF UK</name>
        </Building>
    </Teacher>

    <Teacher>
        <firstName xml:lang="cs">Petra</firstName>
        <lastName xml:lang="cs">Svobodová</lastName>
        <mobileNumber>+420777333444</mobileNumber>
        <salary>62000</salary>
        <Subject>
            <name xml:lang="cs">Databázové systémy</name>
            <code>NDBI025</code>
        </Subject>
        <Building>
            <address xml:lang="cs">Ke Karlovu 3, Praha 2</address>
            <name xml:lang="cs">Matematicko-fyzikální fakulta</name>
        </Building>
    </Teacher>

    <Teacher>
        <firstName xml:lang="cs">Tomáš</firstName>
        <lastName xml:lang="cs">Dvořák</lastName>
        <mobileNumber>+420777555666</mobileNumber>
        <salary>47000</salary>
        <Subject>
            <name xml:lang="cs">Lineární algebra</name>
            <code>NMAI059</code>
        </Subject>
        <Subject>
            <name xml:lang="cs">Matematická analýza</name>
            <code>NMAI052</code>
        </Subject>
        <Building>
            <address xml:lang="cs">Kolejní 1, Praha 6</address>
            <name xml:lang="cs">Studentská kolej</name>
        </Building>
    </Teacher>

</Teachers>
