=== Reblexis/datove-formaty/NPRG036-T3G1-HW3/3/xml/schemas/schema-2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.com/schema-2"
           xmlns="http://www.example.com/schema-2"
           xmlns:tns="http://www.example.com/schema-2"
           xmlns:xml="http://www.w3.org/XML/1998/namespace"
           elementFormDefault="qualified">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="https://www.w3.org/2009/01/xml.xsd" />
    <xs:complexType name="langElement">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="Buildings">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Building" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="address" type="tns:langElement"/>
                            <xs:element name="name" type="tns:langElement"/>
                            <xs:element name="Classroom" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="capacity" type="xs:integer"/>
                                        <xs:element name="name" type="tns:langElement"/>
                                        <xs:element name="Subject" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" type="tns:langElement"/>
                                                    <xs:element name="code" type="xs:string"/>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:anyURI" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:anyURI" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:anyURI" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Reblexis/datove-formaty/NPRG036-T3G1-HW3/3/xml/data/data-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Buildings xmlns="http://www.example.com/schema-2"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.example.com/schema-2 ../schemas/schema-2.xsd">

    <Building id="https://example.org/data/building1">
        <address xml:lang="cs">Malostranské náměstí 25, 118 00 Praha 1</address>
        <name xml:lang="cs">Malostranské náměstí</name>
        <Classroom id="https://example.org/data/classroom1">
            <capacity>150</capacity>
            <name xml:lang="cs">Posluchárna S1</name>
            <Subject id="https://example.org/data/subject1">
                <name xml:lang="cs">Programování I</name>
                <code>NPRG030</code>
            </Subject>
            <Subject id="https://example.org/data/subject3">
                <name xml:lang="cs">Webové technologie</name>
                <code>NPRG036</code>
            </Subject>
        </Classroom>
        <Classroom id="https://example.org/data/classroom2">
            <capacity>80</capacity>
            <name xml:lang="cs">Posluchárna S5</name>
            <Subject id="https://example.org/data/subject2">
                <name xml:lang="cs">Databázové systémy</name>
                <code>NDBI025</code>
            </Subject>
        </Classroom>
    </Building>

    <Building id="https://example.org/data/building2">
        <address xml:lang="cs">Ke Karlovu 3, 121 16 Praha 2</address>
        <name xml:lang="cs">Matematicko-fyzikální fakulta</name>
        <Classroom id="https://example.org/data/classroom3">
            <capacity>40</capacity>
            <name xml:lang="cs">Učebna K11</name>
            <Subject id="https://example.org/data/subject4">
                <name xml:lang="cs">Lineární algebra</name>
                <code>NMAI059</code>
            </Subject>
        </Classroom>
    </Building>

    <Building id="https://example.org/data/building3">
        <address xml:lang="cs">Kolejní 1, 160 00 Praha 6</address>
        <name xml:lang="cs">Studentská kolej</name>
    </Building>

</Buildings>
